### ISSUE TITLE
wrongly tracing of Messages during production

### ISSUE THREAD

**Issue by digitalkaoz** [tideways/symfony-messenger-middleware#4]
Hey,

this middleware wrongly traces the producing of messages as well. While doing that it breaks the tracing of the outer request.

(trace) POST request
                   -> (trace) producing MessageA
                   -> (trace) producing MessageB
                   
in the end we have traces of MessageA and B but a wrong/missing trace for the HTTP Request.

The middleware should only be active when processing Messages and not when producing them.

I think a safeguard like
```php
if (!$envelope->all(ReceivedStamp::class)) {
    // don't profile sent messages, only received
    return $stack->next()->handle($envelope, $stack);
}
```
would be enough? If yes, i could provide the PR.

**Comment by beberlei** [comment]
Indeed, in #3 we already added a second middleware to solve this problem https://github.com/tideways/symfony-messenger-middleware/blob/master/src/TidewaysOnlyConsumedByWorkerMiddleware.php - but this is not yet documented.

**Comment by digitalkaoz** [comment]
thanks @beberlei maybe reading the code would have helped ;)
